"""Change alternative_name to new_name into Example

Revision ID: 8609627976ba
Revises: 242bfb68ab4c
Create Date: 2017-11-14 09:16:46.136896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8609627976ba'
down_revision = '242bfb68ab4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
